name: Tidory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install --no-optional
      - name: Lint JavaScript and Pug files
        run: |
          npm run lint
          pug-lint .  # Add this if not already in npm run lint
        continue-on-error: true  # Optional: continue even if linting fails
      - name: Production build
        run: npm run production
        env:
          TS_SESSION: ${{ secrets.TS_SESSION }}
          URL: ${{ secrets.URL }}