name: Tidory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install --no-optional
      - run: npm run lint
      - name: Build production
        run: npm run production
        env:
          NODE_ENV: production
          TS_SESSION: ${{ secrets.TS_SESSION }}
